[2023-03-22T16:39:59.088+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [queued]>
[2023-03-22T16:39:59.144+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [queued]>
[2023-03-22T16:39:59.145+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:39:59.146+0000] {taskinstance.py:1283} INFO - Starting attempt 29 of 29
[2023-03-22T16:39:59.147+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:39:59.204+0000] {taskinstance.py:1303} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-03-22 08:00:25.425050+00:00
[2023-03-22T16:39:59.228+0000] {standard_task_runner.py:55} INFO - Started process 2597 to run task
[2023-03-22T16:39:59.284+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'manual__2023-03-22T08:00:25.425050+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/minio_s3.py', '--cfg-path', '/tmp/tmpiupjsuyr']
[2023-03-22T16:39:59.309+0000] {standard_task_runner.py:83} INFO - Job 211: Subtask sensor_minio_s3
[2023-03-22T16:39:59.686+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [running]> on host 9783a48d7fca
[2023-03-22T16:39:59.981+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v04
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T08:00:25.425050+00:00
AIRFLOW_CTX_TRY_NUMBER=29
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T08:00:25.425050+00:00
[2023-03-22T16:39:59.985+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T16:40:00.014+0000] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2023-03-22T16:40:00.020+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2023-03-22T16:41:06.111+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T16:42:06.163+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T16:43:06.240+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T16:43:47.867+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-22T16:43:47.898+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2597. PIDs of all processes in the group: [2597]
[2023-03-22T16:43:47.899+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2597
[2023-03-22T16:43:47.901+0000] {taskinstance.py:1482} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-22T16:43:47.952+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2597, status='terminated', exitcode=0, started='16:39:59') (2597) terminated with exit code 0
