[2023-03-17T17:01:51.229+0000] {processor.py:153} INFO - Started process (PID=5623) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:01:51.230+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:01:51.231+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:01:51.231+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:01:51.245+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:01:51.244+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:01:51.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:01:51.281+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.056 seconds
[2023-03-17T17:02:21.889+0000] {processor.py:153} INFO - Started process (PID=5650) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:21.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:02:21.895+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:02:21.894+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:21.910+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:02:21.908+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:02:21.911+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:21.938+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.053 seconds
[2023-03-17T17:02:52.523+0000] {processor.py:153} INFO - Started process (PID=5677) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:52.524+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:02:52.525+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:02:52.525+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:52.537+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:02:52.536+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:02:52.538+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:02:52.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:03:23.297+0000] {processor.py:153} INFO - Started process (PID=5704) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:23.298+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:03:23.299+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:03:23.299+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:23.312+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:03:23.311+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:03:23.312+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:23.336+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:03:53.959+0000] {processor.py:153} INFO - Started process (PID=5731) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:53.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:03:53.963+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:03:53.963+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:53.976+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:03:53.975+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:03:53.977+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:03:54.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.051 seconds
[2023-03-17T17:04:24.649+0000] {processor.py:153} INFO - Started process (PID=5758) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:24.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:04:24.651+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:04:24.651+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:24.665+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:04:24.664+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:04:24.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:24.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:04:55.340+0000] {processor.py:153} INFO - Started process (PID=5785) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:55.342+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:04:55.343+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:04:55.343+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:55.358+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:04:55.357+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:04:55.359+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:04:55.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.049 seconds
[2023-03-17T17:05:26.008+0000] {processor.py:153} INFO - Started process (PID=5812) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:26.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:05:26.011+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:05:26.010+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:26.023+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:05:26.021+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:05:26.024+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:26.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.048 seconds
[2023-03-17T17:05:56.686+0000] {processor.py:153} INFO - Started process (PID=5839) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:56.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:05:56.688+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:05:56.688+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:56.701+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:05:56.700+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:05:56.702+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:05:56.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:06:27.371+0000] {processor.py:153} INFO - Started process (PID=5866) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:27.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:06:27.374+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:06:27.373+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:27.385+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:06:27.384+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:06:27.385+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:27.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:06:58.068+0000] {processor.py:153} INFO - Started process (PID=5893) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:58.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:06:58.074+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:06:58.074+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:58.097+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:06:58.096+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:06:58.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:06:58.121+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.064 seconds
[2023-03-17T17:07:28.696+0000] {processor.py:153} INFO - Started process (PID=5920) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:28.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:07:28.698+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:07:28.698+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:28.710+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:07:28.709+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:07:28.711+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:28.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:07:59.239+0000] {processor.py:153} INFO - Started process (PID=5947) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:59.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:07:59.241+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:07:59.241+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:59.254+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:07:59.253+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:07:59.255+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:07:59.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:08:29.769+0000] {processor.py:153} INFO - Started process (PID=5967) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:08:29.772+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:08:29.774+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:08:29.773+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:08:29.786+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:08:29.785+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:08:29.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:08:29.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.049 seconds
[2023-03-17T17:09:00.342+0000] {processor.py:153} INFO - Started process (PID=5994) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:00.344+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:09:00.345+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:09:00.345+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:00.356+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:09:00.355+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:09:00.357+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:00.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:09:31.028+0000] {processor.py:153} INFO - Started process (PID=6021) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:31.031+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:09:31.034+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:09:31.034+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:31.061+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:09:31.060+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:09:31.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:09:31.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.072 seconds
[2023-03-17T17:10:01.796+0000] {processor.py:153} INFO - Started process (PID=6048) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:01.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:10:01.798+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:10:01.798+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:01.810+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:10:01.809+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:10:01.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:01.837+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:10:32.379+0000] {processor.py:153} INFO - Started process (PID=6075) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:32.380+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:10:32.381+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:10:32.381+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:32.405+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:10:32.403+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:10:32.406+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:10:32.436+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.061 seconds
[2023-03-17T17:11:02.911+0000] {processor.py:153} INFO - Started process (PID=6102) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:02.914+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:11:02.917+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:11:02.916+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:02.934+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:11:02.933+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:11:02.934+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:02.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.070 seconds
[2023-03-17T17:11:33.705+0000] {processor.py:153} INFO - Started process (PID=6129) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:33.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:11:33.707+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:11:33.707+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:33.718+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:11:33.717+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:11:33.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:11:33.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.041 seconds
[2023-03-17T17:12:04.316+0000] {processor.py:153} INFO - Started process (PID=6156) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:04.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:12:04.318+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:12:04.318+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:04.330+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:12:04.329+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:12:04.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:04.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:12:34.961+0000] {processor.py:153} INFO - Started process (PID=6183) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:34.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:12:34.963+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:12:34.963+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:34.976+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:12:34.975+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:12:34.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:12:34.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:13:05.624+0000] {processor.py:153} INFO - Started process (PID=6217) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:05.625+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:13:05.626+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:13:05.626+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:05.640+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:13:05.639+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:13:05.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:05.665+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:13:36.465+0000] {processor.py:153} INFO - Started process (PID=6244) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:36.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:13:36.467+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:13:36.467+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:36.480+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:13:36.479+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:13:36.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:13:36.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:14:07.086+0000] {processor.py:153} INFO - Started process (PID=6271) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:07.087+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:14:07.089+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:14:07.088+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:07.102+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:14:07.101+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:14:07.103+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:07.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:14:37.786+0000] {processor.py:153} INFO - Started process (PID=6298) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:37.787+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:14:37.788+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:14:37.788+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:37.804+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:14:37.802+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:14:37.804+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:14:37.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:15:08.454+0000] {processor.py:153} INFO - Started process (PID=6325) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:08.455+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:15:08.457+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:15:08.456+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:08.470+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:15:08.469+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:15:08.471+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:08.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:15:39.073+0000] {processor.py:153} INFO - Started process (PID=6352) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:39.074+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:15:39.075+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:15:39.075+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:39.093+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:15:39.091+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:15:39.093+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:15:39.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.059 seconds
[2023-03-17T17:16:09.819+0000] {processor.py:153} INFO - Started process (PID=6379) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:09.822+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:16:09.825+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:16:09.824+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:09.853+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:16:09.852+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:16:09.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:09.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.067 seconds
[2023-03-17T17:16:40.528+0000] {processor.py:153} INFO - Started process (PID=6406) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:40.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:16:40.530+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:16:40.530+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:40.544+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:16:40.542+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:16:40.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:16:40.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:17:11.291+0000] {processor.py:153} INFO - Started process (PID=6433) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:11.293+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:17:11.293+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:17:11.293+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:11.303+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:17:11.302+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:17:11.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:11.330+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:17:41.872+0000] {processor.py:153} INFO - Started process (PID=6460) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:41.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:17:41.874+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:17:41.874+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:41.891+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:17:41.890+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:17:41.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:17:41.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.054 seconds
[2023-03-17T17:18:12.496+0000] {processor.py:153} INFO - Started process (PID=6487) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:12.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:18:12.498+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:18:12.498+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:12.513+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:18:12.513+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:18:12.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:12.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:18:43.250+0000] {processor.py:153} INFO - Started process (PID=6514) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:43.252+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:18:43.253+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:18:43.253+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:43.265+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:18:43.264+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:18:43.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:18:43.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:19:13.907+0000] {processor.py:153} INFO - Started process (PID=6541) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:13.909+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:19:13.910+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:19:13.909+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:13.921+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:19:13.920+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:19:13.922+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:13.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:19:44.557+0000] {processor.py:153} INFO - Started process (PID=6568) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:44.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:19:44.559+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:19:44.559+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:44.576+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:19:44.575+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:19:44.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:19:44.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.056 seconds
[2023-03-17T17:20:15.159+0000] {processor.py:153} INFO - Started process (PID=6595) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:15.160+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:20:15.161+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:20:15.161+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:15.177+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:20:15.175+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:20:15.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:15.205+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.053 seconds
[2023-03-17T17:20:45.814+0000] {processor.py:153} INFO - Started process (PID=6622) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:45.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:20:45.816+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:20:45.816+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:45.828+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:20:45.827+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:20:45.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:20:45.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:21:16.471+0000] {processor.py:153} INFO - Started process (PID=6649) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:16.473+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:21:16.476+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:21:16.475+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:16.515+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:21:16.512+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:21:16.516+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:16.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.105 seconds
[2023-03-17T17:21:47.258+0000] {processor.py:153} INFO - Started process (PID=6676) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:47.259+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:21:47.260+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:21:47.260+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:47.272+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:21:47.271+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:21:47.273+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:21:47.300+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:22:18.037+0000] {processor.py:153} INFO - Started process (PID=6703) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:18.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:22:18.039+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:22:18.039+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:18.052+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:22:18.051+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:22:18.052+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:18.078+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:22:48.724+0000] {processor.py:153} INFO - Started process (PID=6730) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:48.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:22:48.730+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:22:48.729+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:48.759+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:22:48.758+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:22:48.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:22:48.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.071 seconds
[2023-03-17T17:23:19.332+0000] {processor.py:153} INFO - Started process (PID=6757) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:19.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:23:19.335+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:23:19.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:19.346+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:23:19.346+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:23:19.347+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:19.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:23:50.002+0000] {processor.py:153} INFO - Started process (PID=6784) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:50.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:23:50.004+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:23:50.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:50.016+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:23:50.015+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:23:50.017+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:23:50.039+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2023-03-17T17:24:20.663+0000] {processor.py:153} INFO - Started process (PID=6811) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:20.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:24:20.668+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:24:20.668+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:20.688+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:24:20.687+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:24:20.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:20.710+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.059 seconds
[2023-03-17T17:24:51.252+0000] {processor.py:153} INFO - Started process (PID=6838) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:51.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:24:51.255+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:24:51.254+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:51.272+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:24:51.271+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:24:51.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:24:51.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.050 seconds
[2023-03-17T17:25:21.981+0000] {processor.py:153} INFO - Started process (PID=6865) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:21.982+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:25:21.983+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:25:21.983+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:21.997+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:25:21.996+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:25:21.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:22.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:25:52.676+0000] {processor.py:153} INFO - Started process (PID=6892) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:52.678+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:25:52.679+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:25:52.679+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:52.691+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:25:52.690+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:25:52.692+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:25:52.722+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.050 seconds
[2023-03-17T17:26:23.300+0000] {processor.py:153} INFO - Started process (PID=6919) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:23.303+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:26:23.306+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:26:23.306+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:23.327+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:26:23.326+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:26:23.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:23.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.058 seconds
[2023-03-17T17:26:54.030+0000] {processor.py:153} INFO - Started process (PID=6946) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:54.032+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:26:54.033+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:26:54.032+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:54.046+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:26:54.045+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:26:54.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:26:54.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:27:24.773+0000] {processor.py:153} INFO - Started process (PID=6973) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:24.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:27:24.775+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:27:24.775+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:24.789+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:27:24.787+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:27:24.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:24.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:27:55.415+0000] {processor.py:153} INFO - Started process (PID=7000) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:55.416+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:27:55.418+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:27:55.417+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:55.433+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:27:55.431+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:27:55.433+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:27:55.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.048 seconds
[2023-03-17T17:28:26.011+0000] {processor.py:153} INFO - Started process (PID=7027) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:26.021+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:28:26.022+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:28:26.022+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:26.042+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:28:26.041+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:28:26.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:26.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.088 seconds
[2023-03-17T17:28:56.535+0000] {processor.py:153} INFO - Started process (PID=7054) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:56.536+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:28:56.537+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:28:56.537+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:56.552+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:28:56.550+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:28:56.553+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:28:56.577+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:29:27.079+0000] {processor.py:153} INFO - Started process (PID=7081) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:27.080+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:29:27.081+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:29:27.081+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:27.094+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:29:27.093+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:29:27.094+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:27.123+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.048 seconds
[2023-03-17T17:29:57.795+0000] {processor.py:153} INFO - Started process (PID=7108) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:57.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:29:57.797+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:29:57.797+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:57.810+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:29:57.809+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:29:57.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:29:57.833+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2023-03-17T17:30:28.530+0000] {processor.py:153} INFO - Started process (PID=7135) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:28.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:30:28.539+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:30:28.539+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:28.569+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:30:28.568+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:30:28.570+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:28.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.072 seconds
[2023-03-17T17:30:59.250+0000] {processor.py:153} INFO - Started process (PID=7162) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:59.252+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:30:59.253+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:30:59.253+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:59.266+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:30:59.265+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:30:59.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:30:59.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:31:29.934+0000] {processor.py:153} INFO - Started process (PID=7189) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:31:29.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:31:29.936+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:31:29.936+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:31:29.947+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:31:29.946+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:31:29.948+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:31:29.974+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:32:00.588+0000] {processor.py:153} INFO - Started process (PID=7216) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:00.589+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:32:00.591+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:32:00.590+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:00.604+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:32:00.603+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:32:00.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:00.632+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:32:31.142+0000] {processor.py:153} INFO - Started process (PID=7243) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:31.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:32:31.144+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:32:31.144+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:31.157+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:32:31.156+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:32:31.157+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:32:31.182+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:33:01.848+0000] {processor.py:153} INFO - Started process (PID=7270) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:01.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:33:01.850+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:33:01.850+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:01.863+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:33:01.862+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:33:01.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:01.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:33:32.478+0000] {processor.py:153} INFO - Started process (PID=7297) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:32.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:33:32.480+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:33:32.480+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:32.495+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:33:32.493+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:33:32.497+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:33:32.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.065 seconds
[2023-03-17T17:34:03.059+0000] {processor.py:153} INFO - Started process (PID=7324) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:03.060+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:34:03.061+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:34:03.061+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:03.075+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:34:03.074+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:34:03.075+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:03.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:34:33.746+0000] {processor.py:153} INFO - Started process (PID=7351) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:33.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:34:33.749+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:34:33.749+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:33.761+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:34:33.760+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:34:33.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:34:33.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:35:04.397+0000] {processor.py:153} INFO - Started process (PID=7378) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:04.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:35:04.399+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:35:04.399+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:04.411+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:35:04.410+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:35:04.411+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:04.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:35:35.048+0000] {processor.py:153} INFO - Started process (PID=7405) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:35.049+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:35:35.050+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:35:35.050+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:35.061+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:35:35.060+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:35:35.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:35:35.087+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:36:05.575+0000] {processor.py:153} INFO - Started process (PID=7432) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:05.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:36:05.577+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:36:05.577+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:05.590+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:36:05.590+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:36:05.591+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:05.616+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:36:36.234+0000] {processor.py:153} INFO - Started process (PID=7459) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:36.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:36:36.237+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:36:36.237+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:36.250+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:36:36.249+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:36:36.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:36:36.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:37:06.901+0000] {processor.py:153} INFO - Started process (PID=7486) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:06.903+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:37:06.905+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:37:06.904+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:06.919+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:37:06.918+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:37:06.920+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:06.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.052 seconds
[2023-03-17T17:37:37.529+0000] {processor.py:153} INFO - Started process (PID=7513) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:37.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:37:37.532+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:37:37.532+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:37.544+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:37:37.543+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:37:37.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:37:37.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:38:08.165+0000] {processor.py:153} INFO - Started process (PID=7540) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:08.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:38:08.167+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:38:08.167+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:08.180+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:38:08.179+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:38:08.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:08.205+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:38:38.839+0000] {processor.py:153} INFO - Started process (PID=7567) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:38.840+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:38:38.842+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:38:38.841+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:38.857+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:38:38.856+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:38:38.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:38:38.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.050 seconds
[2023-03-17T17:39:09.473+0000] {processor.py:153} INFO - Started process (PID=7594) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:09.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:39:09.475+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:39:09.475+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:09.487+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:39:09.486+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:39:09.488+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:09.513+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:39:40.207+0000] {processor.py:153} INFO - Started process (PID=7621) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:40.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:39:40.209+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:39:40.209+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:40.223+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:39:40.222+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:39:40.224+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:39:40.249+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.048 seconds
[2023-03-17T17:40:10.867+0000] {processor.py:153} INFO - Started process (PID=7648) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:10.868+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:40:10.870+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:40:10.869+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:10.882+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:40:10.881+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:40:10.882+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:10.908+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:40:41.488+0000] {processor.py:153} INFO - Started process (PID=7675) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:41.490+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:40:41.491+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:40:41.490+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:41.503+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:40:41.502+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:40:41.503+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:40:41.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:41:12.181+0000] {processor.py:153} INFO - Started process (PID=7702) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:12.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:41:12.184+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:41:12.184+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:12.201+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:41:12.200+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:41:12.202+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:12.249+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.079 seconds
[2023-03-17T17:41:42.980+0000] {processor.py:153} INFO - Started process (PID=7729) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:42.982+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:41:42.983+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:41:42.983+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:42.995+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:41:42.994+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:41:42.996+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:41:43.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:42:13.744+0000] {processor.py:153} INFO - Started process (PID=7756) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:13.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:42:13.746+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:42:13.746+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:13.757+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:42:13.756+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:42:13.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:13.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2023-03-17T17:42:44.382+0000] {processor.py:153} INFO - Started process (PID=7790) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:44.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:42:44.384+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:42:44.384+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:44.396+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:42:44.395+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:42:44.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:42:44.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:43:15.102+0000] {processor.py:153} INFO - Started process (PID=7817) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:15.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:43:15.105+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:43:15.105+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:15.118+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:43:15.117+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:43:15.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:15.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:43:45.683+0000] {processor.py:153} INFO - Started process (PID=7844) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:45.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:43:45.685+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:43:45.685+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:45.697+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:43:45.696+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:43:45.697+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:43:45.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.090 seconds
[2023-03-17T17:44:16.294+0000] {processor.py:153} INFO - Started process (PID=7871) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:16.295+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:44:16.296+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:44:16.296+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:16.310+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:44:16.309+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:44:16.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:16.334+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:44:46.881+0000] {processor.py:153} INFO - Started process (PID=7899) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:46.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:44:46.883+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:44:46.883+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:46.896+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:44:46.895+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:44:46.897+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:44:46.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:45:17.524+0000] {processor.py:153} INFO - Started process (PID=7926) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:17.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:45:17.526+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:45:17.526+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:17.538+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:45:17.537+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:45:17.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:17.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:45:48.126+0000] {processor.py:153} INFO - Started process (PID=7953) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:48.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:45:48.128+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:45:48.127+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:48.140+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:45:48.139+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:45:48.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:45:48.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2023-03-17T17:46:18.824+0000] {processor.py:153} INFO - Started process (PID=7980) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:18.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:46:18.827+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:46:18.827+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:18.839+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:46:18.838+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:46:18.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:18.867+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:46:49.417+0000] {processor.py:153} INFO - Started process (PID=8007) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:49.418+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:46:49.419+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:46:49.419+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:49.431+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:46:49.430+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:46:49.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:46:49.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.043 seconds
[2023-03-17T17:47:20.374+0000] {processor.py:153} INFO - Started process (PID=8035) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:20.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:47:20.376+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:47:20.376+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:20.391+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:47:20.390+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:47:20.391+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:20.415+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:47:50.986+0000] {processor.py:153} INFO - Started process (PID=8062) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:50.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:47:50.990+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:47:50.990+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:51.002+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:47:51.001+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:47:51.002+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:47:51.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.047 seconds
[2023-03-17T17:48:21.678+0000] {processor.py:153} INFO - Started process (PID=8089) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:21.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:48:21.681+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:48:21.681+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:21.693+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:48:21.692+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:48:21.694+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:21.720+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:48:52.320+0000] {processor.py:153} INFO - Started process (PID=8116) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:52.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:48:52.323+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:48:52.323+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:52.334+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:48:52.333+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:48:52.334+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:48:52.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:49:22.890+0000] {processor.py:153} INFO - Started process (PID=8143) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:22.892+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:49:22.893+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:49:22.893+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:22.907+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:49:22.906+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:49:22.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:22.931+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:49:53.469+0000] {processor.py:153} INFO - Started process (PID=8170) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:53.470+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:49:53.471+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:49:53.471+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:53.485+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:49:53.484+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:49:53.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:49:53.511+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:50:24.087+0000] {processor.py:153} INFO - Started process (PID=8197) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:24.088+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:50:24.089+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:50:24.088+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:24.101+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:50:24.100+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:50:24.102+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:24.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.048 seconds
[2023-03-17T17:50:54.743+0000] {processor.py:153} INFO - Started process (PID=8224) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:54.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:50:54.746+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:50:54.746+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:54.765+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:50:54.763+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:50:54.766+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:50:54.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.076 seconds
[2023-03-17T17:51:25.392+0000] {processor.py:153} INFO - Started process (PID=8251) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:25.393+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:51:25.394+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:51:25.394+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:25.406+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:51:25.406+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:51:25.407+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:25.871+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.483 seconds
[2023-03-17T17:51:56.748+0000] {processor.py:153} INFO - Started process (PID=8279) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:56.749+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:51:56.750+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:51:56.749+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:56.762+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:51:56.761+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:51:56.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:51:56.816+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.071 seconds
[2023-03-17T17:52:27.516+0000] {processor.py:153} INFO - Started process (PID=8306) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:27.520+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:52:27.524+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:52:27.523+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:27.551+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:52:27.550+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:52:27.551+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:27.577+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.074 seconds
[2023-03-17T17:52:58.279+0000] {processor.py:153} INFO - Started process (PID=8333) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:58.280+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:52:58.281+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:52:58.281+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:58.293+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:52:58.292+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:52:58.293+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:52:58.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:53:28.892+0000] {processor.py:153} INFO - Started process (PID=8360) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:28.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:53:28.894+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:53:28.894+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:28.906+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:53:28.905+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:53:28.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:28.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:53:59.598+0000] {processor.py:153} INFO - Started process (PID=8387) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:59.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:53:59.606+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:53:59.605+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:59.630+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:53:59.629+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:53:59.630+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:53:59.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.075 seconds
[2023-03-17T17:54:30.357+0000] {processor.py:153} INFO - Started process (PID=8414) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:54:30.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:54:30.359+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:54:30.359+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:54:30.371+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:54:30.370+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:54:30.372+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:54:30.396+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.042 seconds
[2023-03-17T17:55:01.076+0000] {processor.py:153} INFO - Started process (PID=8441) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:01.077+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:55:01.078+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:55:01.078+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:01.093+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:55:01.092+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:55:01.093+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:01.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.045 seconds
[2023-03-17T17:55:31.680+0000] {processor.py:153} INFO - Started process (PID=8468) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:31.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:55:31.682+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:55:31.682+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:31.696+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:55:31.695+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:55:31.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:55:31.720+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.044 seconds
[2023-03-17T17:56:02.333+0000] {processor.py:153} INFO - Started process (PID=8495) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:02.335+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:56:02.336+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:56:02.336+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:02.349+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:56:02.348+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:56:02.350+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:02.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.051 seconds
[2023-03-17T17:56:33.080+0000] {processor.py:153} INFO - Started process (PID=8522) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:33.081+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:56:33.083+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:56:33.082+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:33.096+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:56:33.095+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:56:33.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:56:33.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.046 seconds
[2023-03-17T17:57:03.707+0000] {processor.py:153} INFO - Started process (PID=8549) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:03.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:57:03.709+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:57:03.709+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:03.721+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:57:03.720+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:57:03.721+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:03.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.041 seconds
[2023-03-17T17:57:34.399+0000] {processor.py:153} INFO - Started process (PID=8576) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:34.402+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:57:34.404+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:57:34.404+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:34.426+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:57:34.425+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:57:34.427+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:57:34.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.060 seconds
[2023-03-17T17:58:05.179+0000] {processor.py:153} INFO - Started process (PID=8604) to work on /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:58:05.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_with_python_dependencies.py for tasks to queue
[2023-03-17T17:58:05.181+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:58:05.181+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:58:05.193+0000] {logging_mixin.py:137} INFO - [2023-03-17T17:58:05.192+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_with_python_dependencies.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 23
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-03-17T17:58:05.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_python_dependencies.py
[2023-03-17T17:58:05.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_with_python_dependencies.py took 0.041 seconds
