[2023-03-18T09:55:18.363+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib manual__2023-03-18T09:55:15.652322+00:00 [queued]>
[2023-03-18T09:55:18.380+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_matplotlib manual__2023-03-18T09:55:15.652322+00:00 [queued]>
[2023-03-18T09:55:18.381+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T09:55:18.381+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-18T09:55:18.382+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-18T09:55:18.405+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2023-03-18 09:55:15.652322+00:00
[2023-03-18T09:55:18.411+0000] {standard_task_runner.py:55} INFO - Started process 1243 to run task
[2023-03-18T09:55:18.415+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_matplotlib', 'manual__2023-03-18T09:55:15.652322+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmp5nrsuqwe']
[2023-03-18T09:55:18.418+0000] {standard_task_runner.py:83} INFO - Job 44: Subtask get_matplotlib
[2023-03-18T09:55:18.490+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_matplotlib manual__2023-03-18T09:55:15.652322+00:00 [running]> on host b74962b15d15
[2023-03-18T09:55:18.569+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v02
AIRFLOW_CTX_TASK_ID=get_matplotlib
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T09:55:15.652322+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-18T09:55:15.652322+00:00
[2023-03-18T09:55:18.571+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 18, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2023-03-18T09:55:18.584+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v02, task_id=get_matplotlib, execution_date=20230318T095515, start_date=20230318T095518, end_date=20230318T095518
[2023-03-18T09:55:18.602+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 44 for task get_matplotlib (No module named 'matplotlib'; 1243)
[2023-03-18T09:55:18.628+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-18T09:55:18.647+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
